/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: OGL (https://sketchfab.com/GaryLim)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bb8-droid-8d4f7dbd7dbd476c81e2a4c9bf0664f8
title: BB8 Droid
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.material} />
        <mesh geometry={nodes.mesh_1.geometry} material={materials.material_1} />
        <mesh geometry={nodes.mesh_2.geometry} material={materials.material_2} />
        <mesh geometry={nodes.mesh_3.geometry} material={materials.m7_ref} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
